# Generated by Django 4.2.7 on 2024-07-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.ManyToManyField(blank=True, null=True, related_name='attandance_data', to='API.attendance'),
        ),
    ]
