# Generated by Django 4.2.7 on 2024-07-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_student_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.ManyToManyField(blank=True, related_name='attandance_data', to='API.attendance'),
        ),
    ]
