# Generated by Django 5.0.7 on 2024-08-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignements',
            name='submission_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
